export enum objectTables {
  Buyers = "object_1",
  Supplier = "object_2",
  Account = "object_5",
  BuyerInvoice = "object_45",
  Contract = "object_6",
  ContractInvoice = "object_35",
  SupplierInvoice = "object_44",
  TimeExpense = "object_33",
  lineItems = "object_37",
  contractAmendment = "object_47",
  proposalObject = "object_12",
  Worker = "object_30",
  BusinessUnit = "object_56",
  GLCode = "object_58",
  CostCenter = "object_25",
  BuyerAdmin = "object_24",
  SupplierAdmin = "object_13",
  Requester = "object_20",
  Approver = "object_21",
  BuyerFinance = "object_22",
  SupplierFinance = "object_39",
  Proposer = "object_23",
  Daily_scan = "object_62",
  ProcessLog = "object_68",
}
